<?php
// insert("../datafiles/insert-pro-data.php");
// echo "<br>1 $cod_producto<br>2codigo_barra $codigo_barra<br>3cod_upcean $cod_upcean<br>4cod_categoria $cod_categoria<br>5 $cod_subcategoria<br>6nom_producto $nom_producto<br>7pro_brevedato $pro_brevedato<br>8 $datos_producto<br>9 $cod_proveedor<br>0paisorigen $paisorigen<br>1$brand_marca $brand_marca<br>2precio_compra $precio_compra<br>3precio1_producto $precio1_producto<br>4precio2_producto $precio2_producto<br>5precio3_producto $precio3_producto<br>6precio1_producto $precio4_producto<br>7nom_unidad $nom_unidad<br>8empaque $empaque<br>9fisico $fisico<br>0tamano $tamano<br>1 $peso<br>2 $bultos<br>3 $foto_producto<br>4 $submitted<br>5 activo";
//$query2="insert into productos(cod_producto, cod_almacen, cod_area, cod_item, cod_profit, codigo_barra, cod_upcean, cod_categoria, cod_subcategoria, nom_producto, pro_brevedato, datos_producto, cod_proveedor, brand_marca, precio_compra, compra_dolar, merma_cantidad, merma_tipo, precio1_producto,precio2_producto,precio3_producto,precio4_producto, precio_dolar, iva, stock_antes, stock_actual, stock_despacho, nom_unidad, empaque, fisico, tamano, peso, bultos_producto, cantidad_bultos, minima, maxima, flete, venta, inv_pro, foto_producto, estado, activo)
//values('$cod_producto', '$cod_almacen', '$cod_area', '$cod_item', '$cod_profit', '$codigo_barra', '$cod_upcean', '$cod_categoria', '$cod_subcategoria', '$nom_producto', '$pro_brevedato', '$datos_producto', '$cod_proveedor', '$brand_marca', '$precio_compra', '$compra_dolar', '$merma_cantidad', '$merma_tipo',  '$precioVenta', '$precio2_producto', '$precio3_producto', '$precio4_producto', '$precioDolar', '$iva', '$stock_antes', '$stock_actual', '$stock_despacho', '$nom_unidad', '$empaque', '$fisico', '$tamano', '$peso', '$bultos_producto', '$cantidad_bultos', '$minima', '$maxima', '$flete', '$venta', '$inv_pro', '$foto_producto', '$estado', '$activo')";
if(!isset($estado))
{ $estado=""; }
$query2="insert into productos(cod_producto, codigo_barra, cod_upcean, cod_categoria, cod_subcategoria, nom_producto, pro_brevedato, datos_producto, cod_proveedor, paisorigen, brand_marca, precio_compra, precio1_producto, precio2_producto, precio3_producto, precio4_producto, nom_unidad, empaque, stock_actual, foto_producto, especial, cambia_precio, submitted, estado, activo)
values('$cod_producto', '$codigo_barra', '$cod_upcean', '$cod_categoria', '$cod_subcategoria', '$nom_producto', '$pro_brevedato', '$datos_producto', '$cod_proveedor', '$paisorigen', '$brand_marca', '$precio_compra', '$precio1_producto', '$precio2_producto', '$precio3_producto', '$precio4_producto', '$nom_unidad', '$empaque', '$stock_actual', '$foto_producto', '$especial', '$cambia_precio', '$submitted', '$estado', '$activo')";
$result2=mysqli_query($conex1,$query2);
?>
